# Generated by Django 3.1.2 on 2020-11-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements_weight', models.IntegerField()),
                ('measurements_data', models.DateField()),
            ],
            options={
                'db_table': 'measurements',
            },
        ),
    ]
