# Generated by Django 3.1.2 on 2020-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='measurements_data',
            field=models.TextField(),
        ),
    ]
