# Generated by Django 3.1.2 on 2020-11-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20201103_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'ordering': ['-data']},
        ),
        migrations.RenameField(
            model_name='measurements',
            old_name='measurements_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='measurements',
            old_name='measurements_weight',
            new_name='weight',
        ),
        migrations.AlterModelTable(
            name='measurements',
            table=None,
        ),
    ]
